{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "e0b0c1f9",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No Labels Found\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n",
      "Error getting prediction: Exception encountered when calling Sequential.call().\n",
      "\n",
      "\u001b[1mInput 0 of layer \"dense\" is incompatible with the layer: expected axis -1 of input shape to have value 4608, but received input with shape (1, 86528)\u001b[0m\n",
      "\n",
      "Arguments received by Sequential.call():\n",
      "  • inputs=tf.Tensor(shape=(1, 224, 224, 3), dtype=float32)\n",
      "  • training=False\n",
      "  • mask=None\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import math\n",
    "from cvzone.ClassificationModule import Classifier\n",
    "from cvzone.HandTrackingModule import HandDetector\n",
    "\n",
    "cap = cv2.VideoCapture(0)\n",
    "detector = HandDetector(maxHands=1)\n",
    "\n",
    "# Ensure the file paths are correct\n",
    "try:\n",
    "    classifier = Classifier(\"gesture_model.h5\")\n",
    "except UnicodeDecodeError as e:\n",
    "    print(f\"Error decoding file: {e}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error loading classifier: {e}\")\n",
    "\n",
    "offset = 20\n",
    "imgSize = 300\n",
    "\n",
    "labels = ['call_me','fingers_crossed','up','okay','paper','rock','rock_on','scissor','peace','thumbs']\n",
    "\n",
    "while True:\n",
    "    success, img = cap.read()\n",
    "    if not success:\n",
    "        print(\"Failed to capture image from camera.\")\n",
    "        break\n",
    "\n",
    "    imgOutput = img.copy()\n",
    "    hands, img = detector.findHands(img)\n",
    "    if hands:\n",
    "        hand = hands[0]\n",
    "        x, y, w, h = hand['bbox']\n",
    "\n",
    "        imgWhite = np.ones((imgSize, imgSize, 3), np.uint8) * 255\n",
    "\n",
    "        imgCrop = img[y-offset:y+h+offset, x-offset:x+w+offset]\n",
    "\n",
    "        if imgCrop.size == 0:\n",
    "            print(\"Warning: imgCrop is empty\")\n",
    "            continue\n",
    "\n",
    "        aspectRatio = h / w\n",
    "\n",
    "        if aspectRatio > 1:\n",
    "            k = imgSize / h\n",
    "            wCal = math.ceil(k * w)\n",
    "            if wCal == 0:\n",
    "                print(\"Warning: Invalid width calculation\")\n",
    "                continue\n",
    "\n",
    "            try:\n",
    "                imgResize = cv2.resize(imgCrop, (wCal, imgSize))\n",
    "            except cv2.error as e:\n",
    "                print(f\"Error resizing image: {e}\")\n",
    "                continue\n",
    "\n",
    "            wGap = math.ceil((imgSize - wCal) / 2)\n",
    "            imgWhite[:, wGap:wCal+wGap] = imgResize\n",
    "\n",
    "        else:\n",
    "            k = imgSize / w\n",
    "            hCal = math.ceil(k * h)\n",
    "            if hCal == 0:\n",
    "                print(\"Warning: Invalid height calculation\")\n",
    "                continue\n",
    "\n",
    "            try:\n",
    "                imgResize = cv2.resize(imgCrop, (imgSize, hCal))\n",
    "            except cv2.error as e:\n",
    "                print(f\"Error resizing image: {e}\")\n",
    "                continue\n",
    "\n",
    "            hGap = math.ceil((imgSize - hCal) / 2)\n",
    "            imgWhite[hGap:hCal+hGap, :] = imgResize\n",
    "\n",
    "        try:\n",
    "            prediction, index = classifier.getPrediction(imgWhite, draw=False)\n",
    "        except Exception as e:\n",
    "            print(f\"Error getting prediction: {e}\")\n",
    "            continue\n",
    "\n",
    "        cv2.rectangle(imgOutput, (x-offset, y-offset-70), (x-offset+400, y-offset+60-50), (0, 255, 0), cv2.FILLED)\n",
    "        cv2.putText(imgOutput, labels[index], (x, y-30), cv2.FONT_HERSHEY_COMPLEX, 2, (0, 0, 0), 2)\n",
    "        cv2.rectangle(imgOutput, (x-offset, y-offset), (x+w+offset, y+h+offset), (0, 255, 0), 4)\n",
    "\n",
    "        cv2.imshow('ImageCrop', imgCrop)\n",
    "        cv2.imshow('ImageWhite', imgWhite)\n",
    "\n",
    "    cv2.imshow('Image', imgOutput)\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 3546.814935,
   "end_time": "2023-03-02T09:41:07.345206",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2023-03-02T08:42:00.530271",
   "version": "2.4.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
